### ISSUE TITLE
pasting recursively results in incorrect AR SQL

### ISSUE THREAD

**Issue by jakswa** [agileleague/wherelizer#1]
steps to reproduce:
1. visit http://wherelizer.herokuapp.com/
2. paste in example, `Page.all(:conditions => {:content_id => 5, :name => "Cool"})`
3. copy the result, paste that into the first box, `Page.where(content_id: 5).where(name: "Cool")`
4. witness my creation:
```
Page.where(:content_id => 5).name("Cool").where
```
![image](https://user-images.githubusercontent.com/137793/95616433-c6387580-0a37-11eb-851b-7d7183d6ad5b.png)

**Comment by melindaweathers** [comment]
Thanks for your interest in wherelizer. You appear to be pasting a query that is not valid Rails 2 ActiveRecord syntax into the input box. Also how are things in the year 2013 where I assume you are traveling from?

**Comment by jakswa** [comment]
You are correct! Closing this as invalid.

As far as the year, I don't know what you mean. Is it not 2013 where you are? I just saw the movie Oblivion and Obama is still president. Life is good.

![Jls1](https://user-images.githubusercontent.com/137793/95619050-f41fb900-0a3b-11eb-816d-26e5ee8dd15b.gif)

**Comment by micahwedemeyer** [comment]
Nooooo! Don't close this! We've discovered a time-tunnel! Maybe there's a way I can travel back and reclaim all the hair I've lost?!?!?!

**Comment by jweathers777** [comment]
![image](https://user-images.githubusercontent.com/40768/95630524-00ae0c80-0a50-11eb-8222-51885c8bbdb0.png)

**Comment by johnmaxwell** [comment]
Everyone knows that Rails 3 is way slower than Rails 2 so just stick with 2.
